import { CAPS_SUBJECTS } from '../data/capsTopicCatalog.js';
import {
  MAX_EXERCISE_GENERATION_DAYS as SHARED_MAX_EXERCISE_GENERATION_DAYS,
  MAX_EXERCISES_PER_DATE as SHARED_MAX_EXERCISES_PER_DATE,
  MAX_QUESTIONS_PER_EXERCISE as SHARED_MAX_QUESTIONS_PER_EXERCISE,
  MARKED_TOPIC_MIN_GENERATION_SCORE as SHARED_MARKED_TOPIC_MIN_GENERATION_SCORE,
  MARKED_TOPIC_SUGGESTIONS_PER_SEVEN_EXERCISES as SHARED_MARKED_TOPIC_SUGGESTIONS_PER_SEVEN_EXERCISES,
  TOPICS_PER_EXERCISE_WINDOW_STEP as SHARED_TOPICS_PER_EXERCISE_WINDOW_STEP,
  WEEKLY_EXERCISE_DAYS as SHARED_WEEKLY_EXERCISE_DAYS,
} from '../../functions/src/exerciseGenerationRules.js';

export const ROLES = {
  STUDENT: 'student',
  TUTOR: 'tutor',
  ADMIN: 'admin',
  PARENT: 'parent',
};

export const DEFAULT_SUBJECT = 'Mathematics';

export const SUBJECTS = CAPS_SUBJECTS;

export const SUBJECT = DEFAULT_SUBJECT;

export const SOUTH_AFRICAN_GRADES = [
  'Select Grade',
  'Grade 4',
  'Grade 5',
  'Grade 6',
  'Grade 7',
  'Grade 8',
  'Grade 9',
  'Grade 10',
  'Grade 11',
  'Grade 12',
];

export const PAPER_MONTHS = ['March', 'June', 'September', 'December'];

export const PAPER_NUMBERS = ['Paper 1', 'Paper 2', 'Paper 3', 'Paper 4', 'Examplar'];

export const REGIONS = [
  'National',
  'Eastern Cape',
  'Free State',
  'Gauteng',
  'KwaZulu-Natal',
  'Limpopo',
  'Mpumalanga',
  'North West',
  'Northern Cape',
  'Western Cape',
];

export const MAX_EXERCISES_PER_DATE = SHARED_MAX_EXERCISES_PER_DATE;
export const MAX_QUESTIONS_PER_EXERCISE = SHARED_MAX_QUESTIONS_PER_EXERCISE;
export const MAX_DAILY_EXERCISES = MAX_EXERCISES_PER_DATE;
export const WEEKLY_EXERCISE_DAYS = SHARED_WEEKLY_EXERCISE_DAYS;
export const MAX_EXERCISE_GENERATION_DAYS = SHARED_MAX_EXERCISE_GENERATION_DAYS;
export const TOPICS_PER_EXERCISE_WINDOW_STEP = SHARED_TOPICS_PER_EXERCISE_WINDOW_STEP;
export const MARKED_TOPIC_MIN_GENERATION_SCORE = SHARED_MARKED_TOPIC_MIN_GENERATION_SCORE;
export const MARKED_TOPIC_SUGGESTIONS_PER_SEVEN_EXERCISES = SHARED_MARKED_TOPIC_SUGGESTIONS_PER_SEVEN_EXERCISES;
export const MIN_AI_SOURCE_PAPERS = 2;

export const APP_VERSION = '1.0.0';
