import { useCallback, useEffect, useState } from 'react';
import { Copy, RefreshCw, Tag } from 'lucide-react';
import { AppShell } from '../../components/common/AppShell';
import { useAuth } from '../../hooks/useAuth';
import { createDiscountCode, listDiscountCodes, setDiscountCodeActive } from '../../services/discountCodesService';

const localDateTimeValue = (date) => {
  const offsetDate = new Date(date.getTime() - date.getTimezoneOffset() * 60_000);
  return offsetDate.toISOString().slice(0, 16);
};

const defaultForm = () => ({
  percentOff: '10',
  maxRedemptions: '1',
  restriction: 'none',
  restrictedValue: '',
  startsAt: localDateTimeValue(new Date()),
  expiresAt: '',
  billingDuration: 'first_payment',
});

const formatDate = (value) => value ? new Date(value).toLocaleString() : 'No expiry';
const formatRemaining = (code) => code.remainingUses === null ? 'Unlimited' : `${code.remainingUses} of ${code.maxRedemptions}`;

export const AdminDiscountCodesPage = () => {
  const { profile, logout } = useAuth();
  const [codes, setCodes] = useState([]);
  const [form, setForm] = useState(defaultForm);
  const [status, setStatus] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [workingCode, setWorkingCode] = useState('');

  const refresh = useCallback(async () => {
    setIsLoading(true);
    try {
      const result = await listDiscountCodes();
      setCodes(result.codes || []);
      setStatus('');
    } catch (error) {
      setStatus(error?.message || 'Could not load discount codes.');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  const updateForm = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));

  const handleCreate = async (event) => {
    event.preventDefault();
    setIsSaving(true);
    setStatus('');
    try {
      const payload = {
        percentOff: Number(form.percentOff),
        maxRedemptions: form.maxRedemptions.trim() ? Number(form.maxRedemptions) : null,
        restrictedEmail: form.restriction === 'email' ? form.restrictedValue.trim() : '',
        restrictedAccountId: form.restriction === 'account' ? form.restrictedValue.trim() : '',
        startsAt: new Date(form.startsAt).toISOString(),
        expiresAt: form.expiresAt ? new Date(form.expiresAt).toISOString() : null,
        billingDuration: form.billingDuration,
      };
      const result = await createDiscountCode(payload);
      setForm(defaultForm());
      setStatus(`Discount code ${result.code} created.`);
      await refresh();
    } catch (error) {
      setStatus(error?.message || 'Could not create the discount code.');
    } finally {
      setIsSaving(false);
    }
  };

  const toggleCode = async (code) => {
    setWorkingCode(code.code);
    setStatus('');
    try {
      await setDiscountCodeActive({ code: code.code, active: !code.active });
      await refresh();
    } catch (error) {
      setStatus(error?.message || 'Could not update the discount code.');
    } finally {
      setWorkingCode('');
    }
  };

  const copyCode = async (code) => {
    try {
      await navigator.clipboard.writeText(code);
      setStatus(`Copied ${code}.`);
    } catch {
      setStatus(`Copy failed. Code: ${code}`);
    }
  };

  return (
    <AppShell title="Discount codes" subtitle="Create and manage server-validated subscription discounts." role="admin" user={profile} onLogout={logout}>
      <section className="panel p-5 sm:p-6">
        <div className="flex items-start gap-3">
          <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-lime-400/10 text-lime-300"><Tag className="h-5 w-5" /></span>
          <div>
            <h2 className="text-lg font-bold text-white">Generate a discount code</h2>
            <p className="mt-1 text-sm text-slate-400">Codes are generated by the server, checked for collisions, and use the app’s subscription checkout.</p>
          </div>
        </div>

        <form onSubmit={handleCreate} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          <label className="block"><span className="label">Discount percentage</span><div className="relative"><input className="input pr-10" type="number" min="1" max="100" step="1" required value={form.percentOff} onChange={updateForm('percentOff')} /><span className="absolute right-3 top-3 text-slate-400">%</span></div></label>
          <label className="block"><span className="label">Maximum successful redemptions</span><input className="input" type="number" min="1" step="1" value={form.maxRedemptions} onChange={updateForm('maxRedemptions')} placeholder="Leave blank for unlimited" /><span className="mt-1 block text-xs text-slate-400">In-progress checkouts reserve capacity but do not count as successful.</span></label>
          <label className="block"><span className="label">Who can use it?</span><select className="input" value={form.restriction} onChange={updateForm('restriction')}><option value="none">Anyone eligible</option><option value="email">Specific email</option><option value="account">Specific account ID</option></select></label>
          {form.restriction !== 'none' ? <label className="block"><span className="label">{form.restriction === 'email' ? 'Restricted email address' : 'Restricted account ID'}</span><input className="input" type={form.restriction === 'email' ? 'email' : 'text'} required value={form.restrictedValue} onChange={updateForm('restrictedValue')} /></label> : null}
          <label className="block"><span className="label">Starts at</span><input className="input" type="datetime-local" required value={form.startsAt} onChange={updateForm('startsAt')} /></label>
          <label className="block"><span className="label">Expires at (optional)</span><input className="input" type="datetime-local" value={form.expiresAt} onChange={updateForm('expiresAt')} /></label>
          <label className="block md:col-span-2 xl:col-span-3"><span className="label">Billing duration</span><select className="input" value={form.billingDuration} onChange={updateForm('billingDuration')}><option value="first_payment">First payment only</option><option value="recurring">Initial payment and recurring renewals for the same plan selection</option></select><span className="mt-1 block text-xs text-slate-400">Recurring discounts use Examifying’s backend renewal flow. A 100% recurring discount renews the entitlement as a zero-cost cycle; other zero-cost first checkouts do not create a new Paystack card authorization.</span></label>
          <div className="md:col-span-2 xl:col-span-3"><button className="btn-primary" type="submit" disabled={isSaving}>{isSaving ? 'Creating…' : 'Generate code'}</button></div>
        </form>
      </section>

      <section className="panel mt-5 overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 p-5">
          <div><h2 className="font-bold text-white">Discount codes</h2><p className="mt-1 text-sm text-slate-400">Successful redemptions count only after verified payment or secure zero-cost activation.</p></div>
          <button type="button" className="btn-secondary inline-flex items-center gap-2" onClick={refresh} disabled={isLoading}><RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />Refresh</button>
        </div>
        {status ? <p role="status" className="border-b border-slate-800 px-5 py-3 text-sm text-lime-200">{status}</p> : null}
        <div className="overflow-x-auto">
          <table className="w-full min-w-[1050px] text-left text-sm">
            <thead className="bg-slate-900/70 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Code / discount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Eligibility</th><th className="px-5 py-3">Billing duration</th><th className="px-5 py-3">Starts / expires</th><th className="px-5 py-3">Redemptions</th><th className="px-5 py-3">Remaining</th><th className="px-5 py-3">Action</th></tr></thead>
            <tbody className="divide-y divide-slate-800">
              {codes.map((code) => (
                <tr key={code.code}>
                  <td className="px-5 py-4"><button type="button" className="inline-flex items-center gap-2 font-mono font-bold tracking-wider text-lime-300" onClick={() => copyCode(code.code)}>{code.code}<Copy className="h-3.5 w-3.5" /></button><p className="mt-1 text-xs text-slate-400">{code.percentOff}% off</p></td>
                  <td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${code.status === 'Active' ? 'bg-lime-400/10 text-lime-300' : 'bg-slate-700 text-slate-300'}`}>{code.status}</span></td>
                  <td className="px-5 py-4 text-slate-300">{code.restrictedEmail || (code.restrictedAccountId ? `Account ${code.restrictedAccountId}` : 'Any eligible account')}</td>
                  <td className="px-5 py-4 text-slate-300">{code.billingDuration === 'recurring' ? 'Recurring' : 'First payment'}</td>
                  <td className="px-5 py-4 text-slate-300">{formatDate(code.startsAt)}<br /><span className="text-xs text-slate-500">{formatDate(code.expiresAt)}</span></td>
                  <td className="px-5 py-4 text-slate-300">{code.successfulRedemptions}{code.reservedRedemptions ? <span className="block text-xs text-amber-300">{code.reservedRedemptions} checkout(s) pending</span> : null}</td>
                  <td className="px-5 py-4 text-slate-300">{formatRemaining(code)}</td>
                  <td className="px-5 py-4"><button type="button" className="btn-secondary whitespace-nowrap" disabled={workingCode === code.code || code.status === 'Expired' || code.status === 'Exhausted'} onClick={() => toggleCode(code)}>{workingCode === code.code ? 'Saving…' : code.active ? 'Deactivate' : 'Activate'}</button></td>
                </tr>
              ))}
              {!isLoading && codes.length === 0 ? <tr><td colSpan="8" className="px-5 py-10 text-center text-slate-400">No discount codes created yet.</td></tr> : null}
              {isLoading ? <tr><td colSpan="8" className="px-5 py-10 text-center text-slate-400">Loading discount codes…</td></tr> : null}
            </tbody>
          </table>
        </div>
      </section>
    </AppShell>
  );
};
